baseURL = 'https://camelot-23.github.io/'
languageCode = 'zh-CN'

# website title
# 网站标题
title = 'Elot'

theme = 'dream'


[params]
lightTheme = "emerald"
darkTheme = "forest"
 
#backgroundImage = "bl.jpg"
#backgroundImageDark = "bd.png"
 
#images = ["background.png"]
 
author = "elot"
description = "elot 的生活记录～"
avatar = "/img/avatar/avatar.jpg"
headerTitle = "elot 的博客"
motto = "re"
 
#rss = true

utterancesRepo = "Camelot-23/camelot-23.github.io"

email = "elot@foxmail.com"
 
siteStartYear = 2024
 
favicon = "/ico/E.ico"

# Syntax highlighting
#customSyntaxHighlighting = true

# options
stickyNav = true
showTableOfContents = true
# 在帖子中显示封面图像
showSummaryCoverInPost = true
# 在帖子中显示上一篇和下一篇链接
showPrevNextPost = true
hasTwitterEmbed = false
shareInAside = false

[params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []
 
[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"

[services]
[services.googleAnalytics]
ID = 'G-DXN0QXD4Z0'


